{
 "title": "Netology dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "CPU Load Average",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"} / (1024 * 1024)",
     "legendFormat": "Free Memory MiB"
    }
   ]
  },
  {
   "title": "Free Space on Filesystem",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/\",instance=\"nodeexporter:9100\",job=\"nodeexporter\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Free Space GiB"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\",instance=\"nodeexporter:9100\",job=\"nodeexporter\"} / (1024 * 1024 * 1024)",
     "legendFormat": "Total Space GiB"
    }
   ]
  }
 ]
}