---
- name: Install nginx
  hosts: lighthouse
  handlers:
    - name: Start-nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  tasks:
    - name: Nginx | Install nginx
      become: true
      ansible.builtin.apt:
        name: nginx
        state: present
      notify: Start-nginx
    - name: Nginx | Create config
      become: true
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: "0644"
      notify: Start-nginx
- name: Install lighthouse
  hosts: lighthouse
  handlers:
    - name: Reload-nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  pre_tasks:
    - name: Lighthouse | install dependencies
      become: true
      ansible.builtin.apt:
        name: git
        state: present
  tasks:
    - name: Lighthouse | copy from git
      ansible.builtin.git:
        repo: "https://github.com/VKCOM/lighthouse.git"
        version: master
        dest: /home/makaron/lighthouse
      notify: Reload-nginx
- name: Install Vector
  hosts: vector
  roles:
    - vector
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
