---
- name: Install lighthouse
  hosts: lighthouse
  roles:
    - lighthouse    
- name: Install Vector
  hosts: vector
  roles:
    - vector
- name: Install Clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
