apiVersion: apps/v1
kind: Deployment
metadata:
  name: hwork
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: tools
  template:
    metadata:
      labels:
        app: tools
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        env:
        - name: HTTP_PORT
          value: "80"
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "10080"