#!/bin/bash
REPO="https://github.com/AlekseyStroitelev/docker-practica.git"
DIR="/opt/repo"
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install docker.io -y
sudo apt-get install docker-compose-v2 -y
sudo apt-get install git -y
sudo mkdir /opt/repo
git clone "$REPO" "$DIR"
cd "$DIR"
sudo docker compose up -d