apiVersion: v1 
kind: PersistentVolume
metadata:
  name: pv-local
  namespace: netology
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/pv-local
  persistentVolumeReclaimPolicy: Retain