apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 127.0.0.1
  share: /srv/nfs
reclaimPolicy: Retain
volumeBindingMode: Immediate